### ISSUE TITLE
Feature request: AAA Radius configuration, NTP, timezone

### ISSUE THREAD

**Issue by 2relativ** [aruba/aoscx-ansible-collection#102]
I would like to start a request to support configuring radius server, radius server groups, radius server preshared keys, dynamic authentication, accounting, NTP server and timezone through Ansible modules directly since it seems like the only way is currently to use the aoscx_command module. I know those should be default settings which are not touched that often and maybe could also be set initially through aoscx_config but then again those are such basic things applying to many access switches that those should be their own modules. Because if you have to touch this configuration, you would have a bulk of work and I hope to automate it through Ansible.
Thoughts?

**Comment by alagoutte** [comment]
Big +1 for RADIUS

for NTP already ask on #36 !

**Comment by git4m** [comment]
ntp / timezone configuration can be added eg:

```
    - name: Add static baseline configuration
      connection: ansible.netcommon.network_cli
      arubanetworks.aoscx.aoscx_config:
        lines:
          - ntp server 1.2.3.4 version 3
          - ntp server 5.6.7.8 version 3
          - ntp enable
          - clock timezone utc
        diff_against: running
        save_when: changed
```

verified with with Aruba 6300M running 10.10 software.
