### ISSUE TITLE
Ansible AOSCX collection is not working with AWX Tower

### ISSUE THREAD

**Issue by KaveriNavaleGangurde** [aruba/aoscx-ansible-collection#104]
Hi , 
Trying to run aoscx_command module from AWX but not working. Giving error Couldn't resolve module or action 'aoscx_command'
This often indicates misspelling, missing collection or incorrect module path.
I have installed collection on control node and on AWX container and also installed netcommon 

Please help me on this 
Thanks in advance

**Comment by alagoutte** [comment]
Hi,

Do you have install also requirements ? (pyaoscx...) 

What your playbook ? do you have try to use FCN ? (arubanetworks....aoscx_command ?)

**Comment by tchiapuziowong** [comment]
Do you have the collection [defined in your requirements.yml](https://developer.arubanetworks.com/aruba-aoscx/docs/ansible-automation-platform-overview#defining-the-aos-cx-collection-dependency) in your project repo? For an example you can check out our workflows repo [here](https://github.com/aruba/aoscx-ansible-workflows/blob/main/collections/requirements.yml)

**Comment by KaveriNavaleGangurde** [comment]
Yes I have installed pyapscx and having collection installed in AWX docker, but I am storing my code on Linux control code only not in git

**Comment by tchiapuziowong** [comment]
can you share a copy of your playbook? Are you listing the collection dependency in the playbook itself?
```
---
- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Upload via TFTP
      aoscx_command:
        commands:
        - command: 'copy tftp://10.0.9.87/TL_10_08_0001CN.swi secondary vrf mgmt'
          prompt:
            - '.*Continue.*'
          answer:
            - y
```
