### ISSUE TITLE
Ansible AOSCX Execution Environment for Ansible Automation platform / AWX is not update to date

### ISSUE THREAD

**Issue by uoe-ahewittbell** [aruba/aoscx-ansible-collection#105]
Hi,

I was having issues with ansible playbooks doing a firmware update through AWX due to a pycurl error message.

From investigating it looks like the arubahpe EE created (https://hub.docker.com/r/arubahpe/ansible-aoscx-ee) is not running the latest version of pyaoscx.

I created a workaround by using:

```yml
---
- name: remove legacy pyaoscx
  local_action:
    module: shell
    cmd: pip uninstall pyaoscx -y

- name: install pyaoscx v2.5.1
  local_action:
    module: shell
    cmd: pip install pyaoscx==2.5.1
```

The one in the docker image is set to v2.3.1
