### ISSUE TITLE
Firmware upload not working on 6300 CX switch

### ISSUE THREAD

**Issue by jon-larsen** [aruba/aoscx-ansible-collection#11]
I'm using Ansible to upload firmware. It works fine on a CX 6200F, but it fails on the 6300.
```
---
- hosts: switch
  roles:
    - role: arubanetworks.aoscx_role
  gather_facts: False
  any_errors_fatal: true
  tasks:

# Check current firmware version
    - name: Get current firmware version
      aoscx_facts:
        gather_subset: ['software_version','software_images']
      register: fact_current_version

    - name: Set current_version variable
      set_fact:
        current_version: "{{ fact_current_version['ansible_facts']['ansible_net_software_version'] }}"

    - name: Set image_version variable
      set_fact:
        image_version: "{{ fact_current_version['ansible_facts']['ansible_net_software_images'][boot_partition + '_image_version'] }}"
    - name: show firmware name
      set_fact:
        firmware_file: "{{ firmware_filename }}"

# Upload firmware (unless firmware already exists)
    - name: Upload firmware through local file
      throttle: 1
      aoscx_upload_firmware:
        partition_name: '{{ boot_partition }}'
        firmware_file_path: '/{{ firmware_filename }}'
      when: image_version is not regex('..\.' + firmware)

```

```
TASK [Upload firmware through local file] **********************************************************************************************************
task path: /firmware-upload.yml:27
<switch> attempting to start connection
<switch> using connection plugin arubanetworks.aoscx
<switch> found existing local domain socket, using it!
<switch> 
<switch> local domain socket path is /root/.ansible/pc/a9c72f3811
<switch> ESTABLISH LOCAL CONNECTION FOR USER: root
<switch> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-16651zsoej9ft/ansible-tmp-1634738943.6163135-277936768931481 `" && echo ansible-tmp-1634738943.6163135-277936768931481="` echo /root/.ansible/tmp/ansible-local-16651zsoej9ft/ansible-tmp-1634738943.6163135-277936768931481 `" ) && sleep 0'
Using module file /root/.ansible/roles/arubanetworks.aoscx_role/library/aoscx_upload_firmware.py
<switch> PUT /root/.ansible/tmp/ansible-local-16651zsoej9ft/tmpsxyuo94m TO /root/.ansible/tmp/ansible-local-16651zsoej9ft/ansible-tmp-1634738943.6163135-277936768931481/AnsiballZ_aoscx_upload_firmware.py
<switch> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-16651zsoej9ft/ansible-tmp-1634738943.6163135-277936768931481/ /root/.ansible/tmp/ansible-local-16651zsoej9ft/ansible-tmp-1634738943.6163135-277936768931481/AnsiballZ_aoscx_upload_firmware.py && sleep 0'
<switch> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-local-16651zsoej9ft/ansible-tmp-1634738943.6163135-277936768931481/AnsiballZ_aoscx_upload_firmware.py && sleep 0'
<switch> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-16651zsoej9ft/ansible-tmp-1634738943.6163135-277936768931481/ > /dev/null 2>&1 && sleep 0'
fatal: [switch]: FAILED! => {
    "changed": false,
    "module_stderr": "Killed\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 137
}
```
