### ISSUE TITLE
macOS - No module named 'pyaoscx'

### ISSUE THREAD

**Issue by fre4ki** [aruba/aoscx-ansible-collection#110]
Hey guys,

i'm trying to create a playbook in a python virtual environment on macOS Sonoma and deploy it - but get the message "No module named 'pyaoscx'".

It seems the pyaoscx role is installed but not recognized?

Outputs:

```
**# ansible-galaxy collection list**

# /Users/andreas/.ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        7.0.0
ansible.utils                            5.0.0
arubanetworks.aoscx                      4.4.0
```

```
**# pip list**
Package            Version
------------------ -----------
ansible-pylibssh   1.2.0.post4
bcrypt             4.1.3
certifi            2024.6.2
cffi               1.16.0
charset-normalizer 3.3.2
cryptography       42.0.8
idna               3.7
netaddr            1.3.0
paramiko           3.4.0
pip                24.1.1
pyaoscx            2.6.0
pycparser          2.22
PyNaCl             1.5.0
PyYAML             6.0.1
requests           2.32.3
requests-toolbelt  1.0.0
urllib3            2.2.2
wheel              0.43.0
```

**Inventory File:**
```
❯ cat cx-inv.yml
---
all:
  vars:     #  Global Variables
      ansible_user: admin
      ansible_password: admin
      ansible_network_os: arubanetworks.aoscx.aoscx
      ansible_connection: arubanetworks.aoscx.aoscx  # REST API via pyaoscx connection method
      ansible_aoscx_validate_certs: False
      ansible_aoscx_use_proxy: False
      ansible_acx_no_proxy: True
            #  Switch Variables
      switch_ip_netw:
      switch_ip_mask:
  hosts:
    cx6100:
      ansible_host: 10.10.99.12
```

**Playbook:**
```
❯ cat cx-fw-with-reboot.yml
---
- hosts: cx6100
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: False
  tasks:
    - name: UPLOAD FIRMWARE TO 6100 DEVICES - PRIMARY SLOT
      aoscx_upload_firmware:
        partition_name: 'primary'
        firmware_file_path: '~/Daten/Firmware/Aruba/Switches/6000-6100/ArubaOS-CX_6100-6000_10_13_1020.swi'
    - name: BOOT PRIMARY SLOT
      aoscx_boot_firmware:
        partition_name: 'primary'

- hosts: cx6200
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: False
  tasks:
    - name: UPLOAD FIRMWARE TO 6200 DEVICES - PRIMARY SLOT
      aoscx_upload_firmware:
        partition_name: 'primary'
        firmware_file_path: '~/Daten/Firmware/Aruba/Switches/6200/ArubaOS-CX_6200_10_13_1020.swi'
    - name: BOOT PRIMARY SLOT
      aoscx_boot_firmware:
        partition_name: 'primary'

- hosts: cx6300
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: False
  tasks:
    - name: UPLOAD FIRMWARE TO 6300 DEVICES - PRIMARY SLOT
      aoscx_upload_firmware:
        partition_name: 'primary'
        firmware_file_path: '~/Daten/Firmware/Aruba/Switches/6300-6400/ArubaOS-CX_6400-6300_10_13_1020.swi'
    - name: BOOT PRIMARY SLOT
      aoscx_boot_firmware:
        partition_name: 'primary'
```

**Complete output:**
```
ansible-playbook cx-fw-with-reboot.yml -i cx-inv.yml -vvv
ansible-playbook [core 2.17.1]
  config file = /Users/andreas/.ansible.cfg
  configured module search path = ['/Users/andreas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/10.1.0/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/andreas/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible-playbook
  python version = 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/Cellar/ansible/10.1.0/libexec/bin/python)
  jinja version = 3.1.4
  libyaml = True
Using /Users/andreas/.ansible.cfg as config file
host_list declined parsing /Users/andreas/Documents/Automation/cx-inv.yml as it did not pass its verify_file() method
script declined parsing /Users/andreas/Documents/Automation/cx-inv.yml as it did not pass its verify_file() method
Parsed /Users/andreas/Documents/Automation/cx-inv.yml inventory source with yaml plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: cx-fw-with-reboot.yml ***********************************************************************************
3 plays in cx-fw-with-reboot.yml

PLAY [cx6100] *****************************************************************************************************

TASK [UPLOAD FIRMWARE TO 6100 DEVICES - PRIMARY SLOT] *************************************************************
task path: /Users/andreas/Documents/Automation/cx-fw-with-reboot.yml:9
<10.10.99.12> ESTABLISH LOCAL CONNECTION FOR USER: andreas
<10.10.99.12> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/andreas/.ansible/tmp/ansible-local-2396ymedqelr `"&& mkdir "` echo /Users/andreas/.ansible/tmp/ansible-local-2396ymedqelr/ansible-tmp-1719468600.7857878-2398-2680255875954 `" && echo ansible-tmp-1719468600.7857878-2398-2680255875954="` echo /Users/andreas/.ansible/tmp/ansible-local-2396ymedqelr/ansible-tmp-1719468600.7857878-2398-2680255875954 `" ) && sleep 0'
Using module file /Users/andreas/.ansible/collections/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_upload_firmware.py
<10.10.99.12> PUT /Users/andreas/.ansible/tmp/ansible-local-2396ymedqelr/tmpzom0v7sq TO /Users/andreas/.ansible/tmp/ansible-local-2396ymedqelr/ansible-tmp-1719468600.7857878-2398-2680255875954/AnsiballZ_aoscx_upload_firmware.py
<10.10.99.12> EXEC /bin/sh -c 'chmod u+x /Users/andreas/.ansible/tmp/ansible-local-2396ymedqelr/ansible-tmp-1719468600.7857878-2398-2680255875954/ /Users/andreas/.ansible/tmp/ansible-local-2396ymedqelr/ansible-tmp-1719468600.7857878-2398-2680255875954/AnsiballZ_aoscx_upload_firmware.py && sleep 0'
<10.10.99.12> EXEC /bin/sh -c '/opt/homebrew/Cellar/ansible/10.1.0/libexec/bin/python /Users/andreas/.ansible/tmp/ansible-local-2396ymedqelr/ansible-tmp-1719468600.7857878-2398-2680255875954/AnsiballZ_aoscx_upload_firmware.py && sleep 0'
<10.10.99.12> EXEC /bin/sh -c 'rm -f -r /Users/andreas/.ansible/tmp/ansible-local-2396ymedqelr/ansible-tmp-1719468600.7857878-2398-2680255875954/ > /dev/null 2>&1 && sleep 0'
### The full traceback is:
  File "/var/folders/1y/m5hml76n4m97qvh8gs_rsd500000gn/T/ansible_aoscx_upload_firmware_payload_h9ma3j0w/ansible_aoscx_upload_firmware_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_upload_firmware.py", line 137, in main
    from pyaoscx.device import Device
fatal: [cx6100]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "firmware_file_path": "~/Daten/Firmware/Aruba/Switches/6000-6100/ArubaOS-CX_6100-6000_10_13_1020.swi",
            "partition_name": "primary",
            "remote_firmware_file_path": null,
            "vrf": null,
            "wait_firmware_upload": false
        }
    },
    "msg": "No module named 'pyaoscx'"
}

PLAY RECAP ********************************************************************************************************
cx6100                     : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
