### ISSUE TITLE
Internal Server Error (500) when updating a vlan interface

### ISSUE THREAD

**Issue by simbuerg** [aruba/aoscx-ansible-collection#113]
Hi,

I'm using the ``aoscx.aoscx_vlan_interface`` module to configure multiple IPv4s + Active Gateway IPs on a CX-10000 device.

### Situation:

This snippet is run in a loop for each vlan interface:
```
---
# Example:
vlan_interfaces:
  - admin_state: down
    description:
    vid: 1
    ipv4:
      - 132.231.247.251/22
      - 10.60.255.251/16
    active_gateway_v4:
      - 132.231.247.251
      - 10.60.255.251
...

---
- arubanetworks.aoscx.aoscx_vlan_interface:
    vlan_id: "{{item.vid}}"
    description: "{{item.description}}"
    ipv4: "{{item.ipv4}}"
    admin_state: "{{item.admin_state}}"
    state: create
...
```

If there is an unconfigured vlan interface existing, the module will set the primary and secondary IPv4 just fine. However, as soon as I rerun the task, It will fail with:
```
'GENERIC OPERATION ERROR: Internal service error.\n: Code: 500'
```
The logging output on the switch does not show an error after this.
The interface after the first create looks like this:
```
interface vlan 1
    shutdown
    ip address 132.231.247.251/22
    ip address 10.60.255.251/16 secondary
```

I get the same behavior when running with ``state: update``.
