### ISSUE TITLE
LAG Interface Hash Mode

### ISSUE THREAD

**Issue by wazoo** [aruba/aoscx-ansible-collection#124]
I can't seem to figure out how to set the hash mode (eg: `hash l4-src-dst` ) on a LAG interface using this collection, is it missing?

If so, is that because its missing from pyaoscx as well? I want to open a feature request in the right place so if that is the right place I will do that otherwise please consider this a feature request here.

**Comment by alagoutte** [comment]
Hi Ben,

Yes, this feature missing (like a lot of other missing feature...)

You can also open an issue on pyaoscx

for the moment, the solution is to use aoscx_config

**Comment by wazoo** [comment]
I was trying that the other day and I couldn't get it to work right, I was trying various incantations of this:

```
- name: Configure LAG Hashing Mode
  arubanetworks.aoscx.aoscx_config:
    parents:
      - interface lag {{ item.lag_id }}
    before:
      - config
    lines:
      - "hash {{ item.hash_mode | default('l3-src-dst')}}"
  loop: "{{ switch_lags }}"
```

I am not sure if anyone has a working example, still tinkering with it but just in case!  I also [opened an issue on the pyaoscx project ](https://github.com/aruba/pyaoscx/issues/37) to get it added there if anyone is curious, it seemed to be missing when looking at their code.
