### ISSUE TITLE
rate-limit percent on CX 6100

### ISSUE THREAD

**Issue by solune** [aruba/aoscx-ansible-collection#125]
Hello,

I'm trying to configure l2 interface with an  arubanetworks.aoscx.aoscx_l2_interface task:
```yaml
- name: Tagging uplink interfaces
  arubanetworks.aoscx.aoscx_l2_interface:
    interface: "{{ item }}"
    vlan_trunks: ["{{ vlan }}"]
    vlan_mode: trunk
    state: update
    interface_qos_rate:
      broadcast: 20 percent
      multicast: 80 percent
      unknown-unicast: 10 percent
  loop: "{{ updownlinks }}"
```

With CLI configuration the units accepted by CX6100 on rate limit are kbps and percent:
```
sw61psr11(config-if)# rate-limit broadcast 
  VALUE  Apply a rate <64-10000000> for kbps, or <1-100> for percent
```

But when I run my playbook , I have this error:
```
failed: [sw61psr11] (item=1/1/48) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "description": null,
            "interface": "1/1/48",
            "interface_qos_rate": {
                "broadcast": "20 percent",
                "multicast": "80 percent",
                "unknown-unicast": "10 percent"
            },
            "interface_qos_schedule_profile": null,
            "native_vlan_id": null,
            "native_vlan_tag": null,
            "port_security_client_limit": null,
            "port_security_enable": null,
            "port_security_macs": null,
            "port_security_recovery_time": null,
            "port_security_sticky_learning": null,
            "port_security_sticky_macs": null,
            "port_security_violation_action": null,
            "state": "update",
            "trunk_allowed_all": null,
            "vlan_access": null,
            "vlan_mode": "trunk",
            "vlan_trunks": [
                "1"
            ]
        }
    },
    "item": "1/1/48",
    "msg": "'GENERIC OPERATION ERROR: unknown string: percent, valid strings are: kbps, pps\\n: Code: 400'"
}
```

so I think the collection does not support the specificity of the 6100 which support percent unit.
Marc
