### ISSUE TITLE
aoscx_vlan does not assign VLAN name when using only ID and name 

### ISSUE THREAD

**Issue by br0v** [aruba/aoscx-ansible-collection#13]
Hi,

My playbook uses the aoscx_vlan module to create vlans on a 6300M. The vlans should only have a name and an ID. 

Please see my task below:

```yaml
  - name: Create VLAN10
    aoscx_vlan:
      vlan_id: 10
      name: "I am vlan 10"
```
This task executes successfully, but creates a vlan with a default name instead of the name I supplied in my playbook.

To illustrate this, please see this section from the running config after executing the playbook:
```
vlan 10
    name vlan10
```

I found that vlans which contain the name and the description in the playbook will assign the name which is supplied in the playbook. Meaning that this task will work as expected:
```yaml
  - name: Create VLAN15
    aoscx_vlan:
      vlan_id: 15
      name: "I am vlan 15"
      description: "Does this work?"
```
Again an example from the running config:
```
vlan 15
    name I am vlan 15
    description Does this work?
```
It would be nice to be able to get proper vlan names without having to provide a vlan description.

Regards,

b
