### ISSUE TITLE
Unable to Set Active Gateway on VLAN Interface

### ISSUE THREAD

**Issue by tchiapuziowong** [aruba/aoscx-ansible-collection#21]
The following playbook fails with the following error:
`AttributeError: 'Interface' object has no attribute 'set_active_gateaway'`

```
- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: False
  tasks:
    - name: Create VLAN 200 with name
      aoscx_vlan:
        vlan_id: 200
        name: test
    - name: create L3 interface
      aoscx_vlan_interface:
        vlan_id: 200
        description: test_vlan
        ipv4: ['10.10.9.1/24']
        #active_gateway_ip: '10.10.9.1'
        #active_gateway_mac_v4: '12:01:00:00:01:00'
```

A ticket has been opened internally and we are working to resolve this issue
