### ISSUE TITLE
API Connection doesn't work after restart

### ISSUE THREAD

**Issue by felixblang** [aruba/aoscx-ansible-collection#23]
I'm using the boot_firmware module in my playbook to update my firmware. <br>
Then I wait until the switch is back online, to check if the new firmware version is running correctly. <br>
The Problem is, the API modules seem to try to use the existing socket connection from before the switch restart which leads to the task crashing with Error Code
```
pyaoscx.exceptions.generic_op_error.GenericOperationError: GENERIC OPERATION ERROR: 401 Authorization Required Code: 401
```
I was able to solve a similar problem before when using ssh connections through the ansible meta function reset_connection but this does not work for API connections.

```
- name: Boot to primary
  arubanetworks.aoscx.aoscx_boot_firmware:
    partition_name: 'primary'

- name: Wait for device to come back online
  wait_for:
    host: "{{ ansible_host }}"
    port: 22
    timeout: 600
    delay: 60
  delegate_to: localhost

- name: Check current version
  arubanetworks.aoscx.aoscx_facts:
    gather_subset: 
      - software_images
      - software_version
  register: output
```
