### ISSUE TITLE
aoscx_upload_firmware - RESPONSE ERROR: Invalid URL

### ISSUE THREAD

**Issue by seunay0** [aruba/aoscx-ansible-collection#28]
Hi,
we are trying to update the firmware by uploading the file from local with the following playbook:
```
- name: configure switch using rest api modules
  hosts: aruba-switch
  collections:
    - arubanetworks.aoscx
  
  tasks:
    - name: upgrade switch's firmware
      aoscx_upload_firmware:
        partition_name: secondary
        firmware_file_path: "/home/ansible/cx6000-firmware/ArubaOS-CX_6100-6000_10_10_0002.swi"
```
but we are getting the following error:
```
File \"/home/.local/lib/python3.8/site-packages/pyaoscx/device.py\", line 467, in upload_firmware  
result = self.upload_firmware_local(
 File \"/home/.local/lib/python3.8/site-packages/pyaoscx/device.py\", 
line 429, in upload_firmware_local
 success = utils.file_upload(self.session, firmware_file_path, uri)
 File \"/home/.local/lib/python3.8/site-packages/pyaoscx/utils/util.py\", line 194, in file_upload
    raise ResponseError(\"POST\", e)
pyaoscx.exceptions.response_error.ResponseError: \"RESPONSE ERROR: Invalid URL 'firmware?image=secondary': No schema supplied. Perhaps you meant http://firmware?image=secondary?: Response: POST\"
```
Versions info:
ansible [core 2.12.6]
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True

arubanetworks.aoscx_role, 4.0.0

Basically, just the example reported here https://github.com/aruba/aoscx-ansible-collection/blob/master/docs/aoscx_upload_firmware.md, but no luck.

Any help would be appreciated, thanks!
