### ISSUE TITLE
aoscx_checkpoint: GENERIC OPERATION ERROR: 404 Not Found: Code: 404

### ISSUE THREAD

**Issue by rhizoet** [aruba/aoscx-ansible-collection#33]
When I want to create a checkpoint, I get the following error:
`pyaoscx.exceptions.generic_op_error.GenericOperationError: 'GENERIC OPERATION ERROR: 404 Not Found: Code: 404'`

A few months ago this worked without problems.

In the playbook I try to run the following:

```
- name: Copy running-config to startup-config
  arubanetworks.aoscx.aoscx_checkpoint:
    source_config: "running-config"
    destination_config: "startup-config"
```

I'm using the latest collection and pyaoscx.
