### ISSUE TITLE
Config not saved after changing Banner with module aoscx_banner

### ISSUE THREAD

**Issue by Bernhardvleen** [aruba/aoscx-ansible-collection#53]
Hi, after changing a banner, the new information is only saved to running config, but not to startup - in fact I can not see the changed banner info in any of the available configs, that are listed within switch GUI - but the banner is shown at login. 

These changes are gone after a reboot - only after I run a second play that saves the config explicitly the banner is saved and shows up after reboot and also within config in GUI.

Is this a known behavior? As far as I can tell this does not happen when other modules are used... Do we have to use the module with different parameters?

task that is used to save the config: 

  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli

  tasks:
    - name: save running config
      aoscx_config:
        backup: true
        backup_options:
          filename: backup-{{ ansible_date_time.epoch }}.cfg
          dir_path: /root/
        save_when: always

task for setting banner info is just taken from the examples:
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: Adding or Updating Banner
      aoscx_banner:
        banner_type: banner
        banner: " ==============================================================\n"

Thanks for maintaining this project!

**Comment by tchiapuziowong** [comment]
hi @Bernhardvleen - our REST API modules don't explicitly save to any checkpoint after execution - only [our SSH modules ](https://developer.arubanetworks.com/aruba-aoscx/docs/using-the-aos-cx-ansible-collection#sshcli-modules) have the option to save after execution. based on the example you posted you should explicitly call to save to the startup either using REST API module or SSH module. Here's an example of using the REST API module `aoscx_checkpoint`:
```
- name: Copy running-config to startup-config
  aoscx_checkpoint:
    source_config: 'running-config'
    destination_config: 'startup-config'
```

**Comment by Bernhardvleen** [comment]
hi @tchiapuziowong - many thanks for the quick answer! about the option "destination_config": do you have information if it is possible to target any checkpoint (i.e. not only to running-config or startup-config, but also to something like this: CPC20230110121641_CX6000_6000 (I think those are created automatically but not sure)) I tried with another play but always got error message.

**Comment by Bernhardvleen** [comment]
after testing this, I can inform you with regret, that also this module does not allow to copy configs to any checkpoint - as with the module that works with network_cli connection type, we can only use running_config or startup_config as destination.
Otherwise Error Message like this is shown: 
The error was: pyaoscx.exceptions.generic_op_error.GenericOperationError: 'GENERIC OPERATION ERROR: Error copying configuration. checkpoint name CPC20220727153801_6000_6000 is not allowed\n: Code: 500'

**Comment by Bernhardvleen** [comment]
since the default values for source and destination are exactly as you showed them we can reduce the task to just this: 
---
- name: Save Config from Running to Startup
  aoscx_checkpoint:

**Comment by tchiapuziowong** [comment]
@Bernhardvleen are you sure that checkpoint name exists on the switch? Or that that's a valid checkpoint name? There are limitations to characters I believe. I was able to validate the following with the latest version of the collection:

```
- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
  gather_facts: False
  tasks:
    - name: copy running to new checkpiont
      arubanetworks.aoscx.aoscx_checkpoint:
        destination_config: NEW20230110012148_Access-6_62
        source_config: running-config
    - name: copy existing checkpoint to running
      arubanetworks.aoscx.aoscx_checkpoint:
        source_config: CPC20230110012148_Access-6_6200
        destination_config: running-config
    - name: copy INVALID checkpoint to running - should fail
      arubanetworks.aoscx.aoscx_checkpoint:
        source_config: INVALID_CPC20230110012148
        destination_config: running-config
```
