### ISSUE TITLE
Passive interface ospf_interface and ospf_router

### ISSUE THREAD

**Issue by David7660** [aruba/aoscx-ansible-collection#65]
Hello,

Is it possible to add the ability to configure passive-interface default on a router_ospf and configure "no ip ospf passive" on a ospf interface ?

Thank you,

Regards,

**Comment by tchiapuziowong** [comment]
We have the following method of creating the desired configuration but it's currently throwing an error which our development is investigating internally, but yes this is supported - we'll update this issue once the fix have been pushed. thank you for bringing this to our attention!

```
    - name: Add active_interfaces
      aoscx_ospf_router:
        vrf: default
        instance_tag: 1
        passive_interface_default: true
        active_interfaces: ['1/1/1']
```
